name: Continuous integration
on:
  push:
    branches-ignore:
      - "master"
  pull_request:

jobs:
  build-error-check:
    name: Check build error
    runs-on: ubuntu-latest
    container: python:3.11-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - name: Build documentation
        run: |
          . venv/bin/activate
          sphinx-build -W -j 1 -a -D language='en' -b html . __preview