name: Continuous integration
on:
  push:
    branches-ignore:
      - "master"
  pull_request:

jobs:
  syntax-check:
    name: Check syntax
    runs-on: ubuntu-latest
    container: python:3.11
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Create virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - name: Syntax check
        run: |
          . venv/bin/activate
          rstcheck --recursive --ignore-directives "tabs" fido2/ hsm/ nethsm/ nextbox/ nitrokey3/ nitropad/ nitropc/ nitrophone/ nitrowall/ pro/ software/ start/ storage/ u2f/
  build-error-check:
    name: Check build error
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Create virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
          pip install ./nitrokey-sdk-py
      - name: Build documentation
        run: |
          . venv/bin/activate
          sphinx-build -W -j 1 -a -D language='en' -b html . __preview
